"""Add image_url to Medication model

Revision ID: a4659e78e775
Revises: 88c6e6d7d8e8
Create Date: 2025-10-04 05:03:45.544008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4659e78e775'
down_revision = '88c6e6d7d8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
